version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current # Adjust this path if necessary

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
    - location: scripts/install_codedeploy_agent.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
