name: Trigger AWS CodePipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Trigger-pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger AWS CodePipeline
        uses: aws-actions/aws-codepipeline@v1
        with:
          pipeline-name: bitcube-pipeline
          role-arn: arn:aws:iam::009160050878:role/CodepipelineServiceRole
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1